windows: &windows
   os: windows
   language: generic
matrix:
   include:
      - <<: *windows
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=conanio/gcc49

script:
  - docker ps -a
  - docker images -a
  - docker pull microsoft/windowsservercore
  - docker run microsoft/windowsservercore dir /S /B
